// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
  const ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
  const ElDialog: typeof import('element-plus/es')['ElDialog']
  const ElEmpty: typeof import('element-plus/es')['ElEmpty']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElLoadingDirective: typeof import('element-plus/es')['ElLoadingDirective']
  const ElPagination: typeof import('element-plus/es')['ElPagination']
  const ElRadio: typeof import('element-plus/es')['ElRadio']
  const ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
}
export {}
